In [ ]:
import tensorflow as tf
#ime na gpu uredot
device_name = tf.test.gpu_device_name()

if device_name == '/device:GPU:0':
    print('Najdeno GPU vo: {}'.format(device_name))
else:
    raise SystemError('GPU ured ne e najden')

Najdeno GPU vo: /device:GPU:0


In [ ]:
import torch
# ako ima GPU
if torch.cuda.is_available():    
    #  PyTorch koristi go GPU.    
    device = torch.device("cuda")
    print('Ima %d GPU(s) dostapni.' % torch.cuda.device_count())
    # vajda 1 sekogas
    print('Pytorch ke go koristi GPU:', torch.cuda.get_device_name(0))
# If not...
else:
    print('Nema GPU dostapno, korsistime cpu.')
    device = torch.device("cpu")

Ima 1 GPU(s) dostapni.
Pytorch ke go koristi GPU: Tesla T4


In [ ]:
!pip install transformers





1.   1 mnozestvo 400 primeroci  
2.   2 test mnozestvo 257 primeroci



In [ ]:
import pandas as pd
import numpy as np
# treining_1=pd.read_csv("/content/drive/MyDrive/Dataset_NLP_emocii.csv")
treining_1=pd.read_csv("/content/drive/MyDrive/Dataset_NLP_elena_300.csv")
trening_2=pd.read_csv("/content/drive/MyDrive/dataset_sandra_new_300_emocii.csv")
trening_3=pd.read_csv("/content/drive/MyDrive/golemo-mnozestvo.csv")
test=pd.read_csv("/content/drive/MyDrive/prashanja-60-dodatok.csv")

In [ ]:
treining_1.head()

Questions  ... Sentiment
0  Unexpected loss of my dad, my best friend. Fee...  ...     Grief
1  Unexpected loss of my dad, the person who offe...  ...     Grief
2  I have lost my dad - my favorite person in the...  ...     Grief
3  Unexpected loss of my dad, a person who was tr...  ...     Grief
4   I lost my dog to sudden illness, the grief is...  ...     Grief

[5 rows x 3 columns]

In [ ]:
trening_2.rename(columns={'Emocia': 'Sentiment'}, inplace=True)
trening_2.rename(columns={"Question":"Questions"},inplace=True)
trening_2.rename(columns={"Answer":"Answers"},inplace=True)
trening_2.head()

Questions  ...  Sentiment
0               I need help with abusive neighbor  ...       fear
1               I need help with abusive neighbor  ...       faer
2               I need help with abusive neighbor  ...       fear
3  \n\n \nIs the MBTi test accurate and reliable?  ...  curiosity
4         Is the MBTi test accurate and reliable?  ...  curiosity

[5 rows x 3 columns]

In [ ]:
len(trening_3)

2129

In [ ]:
trening_3.head()

Questions  ...                                            Answers
0  I'm going through some things with my feelings...  ...  If everyone thinks you're worthless, then mayb...
1  I'm going through some things with my feelings...  ...  Hello, and thank you for your question and see...
2  I'm going through some things with my feelings...  ...  First thing I'd suggest is getting the sleep y...
3  I'm going through some things with my feelings...  ...  Therapy is essential for those that are feelin...
4  I'm going through some things with my feelings...  ...  I first want to let you know that you are not ...

[5 rows x 3 columns]

In [ ]:
trening_3.Sentiment.unique()

array(['depression', 'anxiety', 'parenting', 'self-esteem',
       'relationship-dissolution', 'workplace-relationships',
       'spirituality', 'trauma', 'domestic-violence', 'anger-management',
       'sleep-improvement', 'intimacy', 'grief-and-loss',
       'substance-abuse', 'family-conflict', 'marriage',
       'eating-disorders', 'relationships', 'lgbtq', 'behavioral-change',
       'addiction', 'legal-regulatory', 'professional-ethics', 'stress',
       'human-sexuality', 'social-relationships', 'children-adolescents',
       'military-issues', 'self-harm', 'diagnosis',
       'counseling-fundamentals'], dtype=object)

In [ ]:
trening = pd.concat([treining_1, trening_2], ignore_index=True, sort=False)


In [ ]:
trening = pd.concat([trening, trening_3], ignore_index=True, sort=False)

In [ ]:
from sklearn.model_selection import train_test_split

trening, test_2 = train_test_split(trening, test_size=0.2)


In [ ]:
len(test_2)

546

In [ ]:
test_2

Questions  ...                                            Answers
2429  I was “mentored” by this guy for a few years s...  ...  It doesn't really matter what the actual diagn...
857   I'm starting to think that I might have depres...  ...  It is possible that you have depression, but y...
1274  I am in my early 20s and I still live with my ...  ...  Unfortunately you seem to have yourself in a d...
437                 How do you keep a positive mindset?  ...                         Try not to expect results.
1321  What makes my step child, an 8 year old boy, c...  ...  I can see why you are alarmed. That is a scary...
...                                                 ...  ...                                                ...
290       Should I tell the guy I like that I like him?  ...                                                NaN
1071  I'm just an extremely paranoid person. I const...  ...  One approach is to be more accepting of yourse...
2331  For the past four weeks, I've been having nigh...  ...  I would recommend that you talk with a mental ...
311                                     I feel so lost.  ...  Use Your Lost and Loneliness as a Self-Directi...
503                             i have a fear of blood.  ...  Vasovagal syncope (vay-zoh-VAY-gul SING-kuh-pe...

[546 rows x 4 columns]

In [ ]:
trening.Sentiment=trening['Sentiment'].str.lower()
trening.Sentiment.unique()

array(['anxiety', 'diagnosis', 'domestic-violence',
       'counseling-fundamentals', 'depression', 'workplace-relationships',
       'behavioral-change', 'relationships', 'love', 'grief', 'happiness',
       'marriage', 'parenting', 'self-esteem', 'intimacy',
       'relationship-dissolution', 'family-conflict', 'curiosity',
       'anger-management', 'substance-abuse', 'lgbtq', 'fear',
       'grief-and-loss', 'professional-ethics', 'trauma', 'happy',
       'social-relationships', nan, 'spirituality',
       'children-adolescents', 'military-issues', 'sleep-improvement',
       'self-harm', 'addiction', 'eating-disorders', 'human-sexuality',
       'stress', 'legal-regulatory', 'faer'], dtype=object)

In [ ]:
trening.Sentiment.replace("happiness","happy",inplace=True)

In [ ]:
trening.Sentiment.replace("faer","fear",inplace=True)
trening.Sentiment.unique()

array(['anxiety', 'diagnosis', 'domestic-violence',
       'counseling-fundamentals', 'depression', 'workplace-relationships',
       'behavioral-change', 'relationships', 'love', 'grief', 'happy',
       'marriage', 'parenting', 'self-esteem', 'intimacy',
       'relationship-dissolution', 'family-conflict', 'curiosity',
       'anger-management', 'substance-abuse', 'lgbtq', 'fear',
       'grief-and-loss', 'professional-ethics', 'trauma',
       'social-relationships', nan, 'spirituality',
       'children-adolescents', 'military-issues', 'sleep-improvement',
       'self-harm', 'addiction', 'eating-disorders', 'human-sexuality',
       'stress', 'legal-regulatory'], dtype=object)

In [ ]:
trening['Sentiment'].isnull().values.sum()
# poso imase 1 
trening.Sentiment.replace(np.nan,"love",inplace=True)
# ovoj red cisto da ja sredam rabotata
trening.Sentiment.unique()


array(['anxiety', 'diagnosis', 'domestic-violence',
       'counseling-fundamentals', 'depression', 'workplace-relationships',
       'behavioral-change', 'relationships', 'love', 'grief', 'happy',
       'marriage', 'parenting', 'self-esteem', 'intimacy',
       'relationship-dissolution', 'family-conflict', 'curiosity',
       'anger-management', 'substance-abuse', 'lgbtq', 'fear',
       'grief-and-loss', 'professional-ethics', 'trauma',
       'social-relationships', 'spirituality', 'children-adolescents',
       'military-issues', 'sleep-improvement', 'self-harm', 'addiction',
       'eating-disorders', 'human-sexuality', 'stress',
       'legal-regulatory'], dtype=object)

In [ ]:
test.rename(columns={'Emotiton': 'Sentiment',"Question":"Questions"}, inplace=True)
test.head()
test.Sentiment[2]='fear'
test = pd.concat([test, test_2], ignore_index=True, sort=False)
# test = pd.concat([test, test_3], ignore_index=True, sort=False)
# test = pd.concat([test, test_4], ignore_index=True, sort=False)

In [ ]:
test.Sentiment=test['Sentiment'].str.lower()


In [ ]:
test.Sentiment.unique()

array(['fear', 'grief', 'love', 'curiosity', 'social-relationships',
       'depression', 'parenting', 'happy', 'relationship-dissolution',
       'intimacy', 'family-conflict', 'lgbtq', 'self-harm', 'trauma',
       'behavioral-change', 'counseling-fundamentals', 'relationships',
       'domestic-violence', 'substance-abuse', 'self-esteem', 'happiness',
       'anxiety', 'marriage', 'grief-and-loss', 'workplace-relationships',
       'professional-ethics', 'spirituality', 'anger-management',
       'diagnosis', 'sleep-improvement', nan, 'eating-disorders',
       'legal-regulatory', 'stress', 'addiction', 'children-adolescents'],
      dtype=object)

In [ ]:
trening.Sentiment.unique()

array(['anxiety', 'diagnosis', 'domestic-violence',
       'counseling-fundamentals', 'depression', 'workplace-relationships',
       'behavioral-change', 'relationships', 'love', 'grief', 'happy',
       'marriage', 'parenting', 'self-esteem', 'intimacy',
       'relationship-dissolution', 'family-conflict', 'curiosity',
       'anger-management', 'substance-abuse', 'lgbtq', 'fear',
       'grief-and-loss', 'professional-ethics', 'trauma',
       'social-relationships', 'spirituality', 'children-adolescents',
       'military-issues', 'sleep-improvement', 'self-harm', 'addiction',
       'eating-disorders', 'human-sexuality', 'stress',
       'legal-regulatory'], dtype=object)

In [ ]:
test.Sentiment.replace("happiness","happy",inplace=True)
test.Sentiment.replace(np.nan,"love",inplace=True)


Ovde mestam sentaces=Questions delot
labels=Sentiment delot

In [ ]:
# # ['grief'=0,
#  'curiosity'=1, 
#  'love'=2, 
#  'fear'=3
#  , 'happy'=4
#  ]
# zakodirani vrednosti
# 'depression'=5,
#  'anxiety' =6, 'parenting'=7, 'self-esteem'=8, 'relationship-dissolution'=9,
#  'workplace-relationships' = 10, 'spirituality' = 11, 'trauma' = 12, 
#  'domestic-violence' =13, 'anger-management' = 14, 'sleep-improvement' = 15,
#  'intimacy'=16, 'grief-and-loss'=17, 'substance-abuse'=18, 'family-conflict'=19
#  'marriage'=20,
      #  'eating-disorders' =21, 'relationships' 22, 'lgbtq' 23, 'behavioral-change' 24,
      #  'addiction'25, 'legal-regulatory'26, 'professional-ethics' 27, 'stress' 28,
      #  'human-sexuality' 29, 'social-relationships' 30, 'children-adolescents' 31,
      #  'military-issues' 32, 'self-harm' =33, 'diagnosis' =34,
      #  'counseling-fundamentals =35'

trening.Sentiment.replace('grief',0,inplace=True)
trening.Sentiment.replace('curiosity',1,inplace=True)
trening.Sentiment.replace('love',2,inplace=True)
trening.Sentiment.replace('fear',3,inplace=True)
trening.Sentiment.replace('happy',4,inplace=True)
trening.Sentiment.replace('depression',5,inplace=True)
trening.Sentiment.replace('anxiety',6,inplace=True)
trening.Sentiment.replace('parenting',7,inplace=True)
trening.Sentiment.replace('self-esteem',8,inplace=True)
trening.Sentiment.replace('relationship-dissolution',9,inplace=True)
trening.Sentiment.replace('workplace-relationships',10,inplace=True)
trening.Sentiment.replace('spirituality',11,inplace=True)
trening.Sentiment.replace('trauma',12,inplace=True)
trening.Sentiment.replace('domestic-violence',13,inplace=True)
trening.Sentiment.replace('anger-management',14,inplace=True)
trening.Sentiment.replace('sleep-improvement',15,inplace=True)
trening.Sentiment.replace('intimacy',16,inplace=True)
trening.Sentiment.replace('grief-and-loss',17,inplace=True)
trening.Sentiment.replace('substance-abuse',18,inplace=True)
trening.Sentiment.replace('family-conflict',19,inplace=True)
trening.Sentiment.replace('marriage',20,inplace=True)
trening.Sentiment.replace('eating-disorders',21,inplace=True)
trening.Sentiment.replace('relationships',22,inplace=True)
trening.Sentiment.replace('lgbtq',23,inplace=True)
trening.Sentiment.replace('behavioral-change',24,inplace=True)
trening.Sentiment.replace('addiction',25,inplace=True)
trening.Sentiment.replace('legal-regulatory',26,inplace=True)
trening.Sentiment.replace('professional-ethics',27,inplace=True)
trening.Sentiment.replace('stress',28,inplace=True)
trening.Sentiment.replace('human-sexuality',29,inplace=True)
trening.Sentiment.replace('social-relationships',30,inplace=True)
trening.Sentiment.replace('children-adolescents',31,inplace=True)
trening.Sentiment.replace('military-issues',32,inplace=True)
trening.Sentiment.replace('self-harm',33,inplace=True)
trening.Sentiment.replace('diagnosis',34,inplace=True)
trening.Sentiment.replace('counseling-fundamentals',35,inplace=True)


In [ ]:
trening.Sentiment.unique()

array([ 6, 34, 13, 35,  5, 10, 24, 22,  2,  0,  4, 20,  7,  8, 16,  9, 19,
        1, 14, 18, 23,  3, 17, 27, 12, 30, 11, 31, 32, 15, 33, 25, 21, 29,
       28, 26])

In [ ]:

test.Sentiment.replace('grief',0,inplace=True)
test.Sentiment.replace('curiosity',1,inplace=True)
test.Sentiment.replace('love',2,inplace=True)
test.Sentiment.replace('fear',3,inplace=True)
test.Sentiment.replace('happy',4,inplace=True)
test.Sentiment.replace('depression',5,inplace=True)
test.Sentiment.replace('anxiety',6,inplace=True)
test.Sentiment.replace('parenting',7,inplace=True)
test.Sentiment.replace('self-esteem',8,inplace=True)
test.Sentiment.replace('relationship-dissolution',9,inplace=True)
test.Sentiment.replace('workplace-relationships',10,inplace=True)
test.Sentiment.replace('spirituality',11,inplace=True)
test.Sentiment.replace('trauma',12,inplace=True)
test.Sentiment.replace('domestic-violence',13,inplace=True)
test.Sentiment.replace('anger-management',14,inplace=True)
test.Sentiment.replace('sleep-improvement',15,inplace=True)
test.Sentiment.replace('intimacy',16,inplace=True)
test.Sentiment.replace('grief-and-loss',17,inplace=True)
test.Sentiment.replace('substance-abuse',18,inplace=True)
test.Sentiment.replace('family-conflict',19,inplace=True)
test.Sentiment.replace('marriage',20,inplace=True)
test.Sentiment.replace('eating-disorders',21,inplace=True)
test.Sentiment.replace('relationships',22,inplace=True)
test.Sentiment.replace('lgbtq',23,inplace=True)
test.Sentiment.replace('behavioral-change',24,inplace=True)
test.Sentiment.replace('addiction',25,inplace=True)
test.Sentiment.replace('legal-regulatory',26,inplace=True)
test.Sentiment.replace('professional-ethics',27,inplace=True)
test.Sentiment.replace('stress',28,inplace=True)
test.Sentiment.replace('human-sexuality',29,inplace=True)
test.Sentiment.replace('social-relationships',30,inplace=True)
test.Sentiment.replace('children-adolescents',31,inplace=True)
test.Sentiment.replace('military-issues',32,inplace=True)
test.Sentiment.replace('self-harm',33,inplace=True)
test.Sentiment.replace('diagnosis',34,inplace=True)
test.Sentiment.replace('counseling-fundamentals',35,inplace=True)

In [ ]:
trening.Sentiment.unique()

array([ 6, 34, 13, 35,  5, 10, 24, 22,  2,  0,  4, 20,  7,  8, 16,  9, 19,
        1, 14, 18, 23,  3, 17, 27, 12, 30, 11, 31, 32, 15, 33, 25, 21, 29,
       28, 26])

In [ ]:
# Get the lists of sentences and their labels.
sentences = trening.Questions.values
labels = trening.Sentiment.values

Bert delot veke


In [ ]:
from transformers import BertTokenizer
# Loadiranje na bert tokenizer
print('BERT tokenizer se loadira...')
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased', do_lower_case=True)

BERT tokenizer se loadira...


In [ ]:
# CLS poceten token ,SEP kraen.
# 512 max tokens

In [ ]:
# Tokeniziraqj gi site recenici i mapiraj gi tokenite so id na zborovi
input_ids = []
# Za sekoja recenica...
for sent in sentences:
    # `encode` ke:
    #   (1) Tokenizira recenica.
    #   (2) prilepi`[CLS]` na start.
    #   (3) prilepi `[SEP]`na kraj.
    #   (4) mapiraj token vo zbor id.
    encoded_sent = tokenizer.encode(
                        sent,                      # recenici za enkodiranje.
                        add_special_tokens = True, # dodaj '[CLS]' i '[SEP]'
                   
                   )
    
    # dodaj enkodirani recenici vo listata.
    input_ids.append(encoded_sent)
# isprintaj samo prva recenica(proverka pravime).
print('Originalna recenica: ', sentences[0])
print('Tokenizirani ID:', input_ids[0])

In [ ]:
print('Max golemina na recenica: ', max([len(sen) for sen in input_ids]))

Max golemina na recenica:  657


In [ ]:
from keras.preprocessing.sequence import pad_sequences
# postavuvame max golemina na recenica.
MAX_LEN = 220
print('\ndodavanje/namaluvanje na sire recenici na golemina  %d ...' % MAX_LEN)
print('\nPadding token: "{:}", ID: {:}'.format(tokenizer.pad_token, tokenizer.pad_token_id))
# Pad our input tokens with value 0.
# "post" znaci deka sakame da dovame i kratime od kraj na recenica ne od pocetok
input_ids = pad_sequences(input_ids, maxlen=MAX_LEN, dtype="long", 
                          value=0, truncating="post", padding="post")
print('\Gotovo.')


dodavanje/namaluvanje na sire recenici na golemina  220 ...

Padding token: "[PAD]", ID: 0
\Gotovo.


In [ ]:
# kreirame attention masks
attention_masks = []
# Za sekoja recenica...
for sent in input_ids:
    
    # Kreiraj  attention mask.
    #   - Ako  token ID e 0, togas e samo pocetniot token "pad", stavi ja  maskata na 0.
    #   - Ako  token ID > 0, togas e vistinski token t.e biten zbor , stavi ja  maskata na  1.
    att_mask = [int(token_id > 0) for token_id in sent]
    
    # Soberi gi attention mask za ovaa recenica.
    attention_masks.append(att_mask)

In [ ]:
# Koristime train_test_split za da ja podelime nasata lista vo  train i validation m-va za treniranje
from sklearn.model_selection import train_test_split
# koristime 90% za training i 10% za validation.
train_inputs, validation_inputs, train_labels, validation_labels = train_test_split(input_ids, labels, 
                                                            random_state=2018, test_size=0.1)
#isto i za maskite.
train_masks, validation_masks, _, _ = train_test_split(attention_masks, labels,
                                             random_state=2018, test_size=0.1)

In [ ]:
# konveritrame nympay.arrays vo puthorch 
# konveritrame site  inputs i labels vo t.e torch tensors, baraniot tip na podatoci 
# za nasiot model.
train_inputs = torch.tensor(train_inputs)
validation_inputs = torch.tensor(validation_inputs)
train_labels = torch.tensor(train_labels)
validation_labels = torch.tensor(validation_labels)
train_masks = torch.tensor(train_masks)
validation_masks = torch.tensor(validation_masks)

In [ ]:
# nie isto taka kreiravme iterator za  m-vo koristejki torch DataLoader class. 
# ova stedi memorija za vreme na trainingot zatoa sto za razlika od for loop,  iteratortorot ne mora da go lodira celoto m-vo vo memorija 

from torch.utils.data import TensorDataset, DataLoader, RandomSampler, SequentialSampler
# The DataLoader treba da ja znae  batch size za training, pa ja specificirame

batch_size = 32
# Kreirame DataLoader za  training m-vo.
train_data = TensorDataset(train_inputs, train_masks, train_labels)
train_sampler = RandomSampler(train_data)
train_dataloader = DataLoader(train_data, sampler=train_sampler, batch_size=batch_size)
#  Kreirame DataLoader za validation m-vo.
validation_data = TensorDataset(validation_inputs, validation_masks, validation_labels)
validation_sampler = SequentialSampler(validation_data)
validation_dataloader = DataLoader(validation_data, sampler=validation_sampler, batch_size=batch_size)

In [ ]:
from transformers import BertForSequenceClassification, AdamW, BertConfig
# Loadirame BertForSequenceClassification, pretrained BERT model so eden linear classification layer on top. 

model = BertForSequenceClassification.from_pretrained(
    "bert-base-uncased", # koristime 12-layer BERT model, so  uncased vocab.
    num_labels = 36, # Tbr izlezni koloni =5 za muliti klasna klasifikacija.
    output_attentions = False, # dali da vrakja  attentions golemini
    output_hidden_states = False, # dali da vrakja  hidden-states.
)
# kazi na  pytorch da go ranuva model na GPU.
model.cuda()

In [ ]:
# site parametri na modelot kako lista od torki.
params = list(model.named_parameters())
print('BERT model ima {:} razlicno imenuvani parametri.\n'.format(len(params)))
print('==== Embedding Layer ====\n')
for p in params[0:5]:
    print("{:<55} {:>12}".format(p[0], str(tuple(p[1].size()))))
print('\n==== First Transformer ====\n')
for p in params[5:21]:
    print("{:<55} {:>12}".format(p[0], str(tuple(p[1].size()))))
print('\n==== Output Layer ====\n')
for p in params[-4:]:
    print("{:<55} {:>12}".format(p[0], str(tuple(p[1].size()))))

BERT model ima 201 razlicno imenuvani parametri.

==== Embedding Layer ====

bert.embeddings.word_embeddings.weight                  (30522, 768)
bert.embeddings.position_embeddings.weight                (512, 768)
bert.embeddings.token_type_embeddings.weight                (2, 768)
bert.embeddings.LayerNorm.weight                              (768,)
bert.embeddings.LayerNorm.bias                                (768,)

==== First Transformer ====

bert.encoder.layer.0.attention.self.query.weight          (768, 768)
bert.encoder.layer.0.attention.self.query.bias                (768,)
bert.encoder.layer.0.attention.self.key.weight            (768, 768)
bert.encoder.layer.0.attention.self.key.bias                  (768,)
bert.encoder.layer.0.attention.self.value.weight          (768, 768)
bert.encoder.layer.0.attention.self.value.bias                (768,)
bert.encoder.layer.0.attention.output.dense.weight        (768, 768)
bert.encoder.layer.0.attention.output.dense.bias              (76

In [ ]:
# Note: AdamW e klasa za uggingface library (sprotivno na  pytorch) 

optimizer = AdamW(model.parameters(),
                  lr = 2e-5, # args.learning_rate - defoltni se  5e-5,nie korsitime 2e-5
                  eps = 1e-8 # args.adam_epsilon  - defoltni se 1e-8.
                )
from transformers import get_linear_schedule_with_warmup
# broj training epohi 
epochs = 15
# Totalen broj na training cekori e broj  dobien kako batches * number of epochs.
total_steps = len(train_dataloader) * epochs
# kreiraj  skedzuler za rate na ucenje.
scheduler = get_linear_schedule_with_warmup(optimizer, 
                                            num_warmup_steps = 0,
                                            num_training_steps = total_steps)

In [ ]:
import numpy as np
# funkcija za presmetka na accuracy/tocnost na  predictions vs labels /predviduvanja vs tocni labeli
def flat_accuracy(preds, labels):
    pred_flat = np.argmax(preds, axis=1).flatten()
    labels_flat = labels.flatten()
    return np.sum(pred_flat == labels_flat) / len(labels_flat)

In [ ]:
import time
import datetime
def format_time(elapsed):
    '''
    zema vreme vo sekundi i vrakaja string hh:mm:ss
    '''
    # Round na najbliska sec.
    elapsed_rounded = int(round((elapsed)))
    
    # Format  hh:mm:ss
    return str(datetime.timedelta(seconds=elapsed_rounded))

In [ ]:
import random

seed_val = 42
random.seed(seed_val)
np.random.seed(seed_val)
torch.manual_seed(seed_val)
torch.cuda.manual_seed_all(seed_val)
# cuvaj/skladiraj average loss posle sekoja epoha za da mozeme da gi prikazeme (plot them)
loss_values = []
# za sekoja epoha...
for epoch_i in range(0, epochs):
    
    # ========================================
    #               Training
    # ========================================
    
    # izvedi eden full pass preku training set.
    print("")
    print('======== Epoch {:} / {:} ========'.format(epoch_i + 1, epochs))
    print('Training...')
    # meri kolu vreme zema trening epohata 
    t0 = time.time()
    # Resetiraj total loss za ovaa epoha.
    total_loss = 0
    # stavi go modelot vo training mode t.e treniraj
    model.train()
    # za sekoj batch na training data...
    for step, batch in enumerate(train_dataloader):
        # Progresot se abdejtira na sekoi  40 batches.
        if step % 40 == 0 and not step == 0:
            # Presmetuvanje na vremeto vo minuti 
            elapsed = format_time(time.time() - t0)
            
            # PRikaz na progresot.
            print('  Batch {:>5,}  of  {:>5,}.    Elapsed: {:}.'.format(step, len(train_dataloader), elapsed))
        # Otpakuvanje na trening batch od dataloader iteratorot. 
        #
        # So to metodot se zema sekoj tensor.
        #
        # `batch` sodrzi 3 pytorch tensors:
        #   [0]: input ids 
        #   [1]: attention masks
        #   [2]: labels 
        b_input_ids = batch[0].to(device)
        b_input_mask = batch[1].to(device)
        b_labels = batch[2].to(device)
        # sekogas izbrisi prethodni merenja/kalkulacii na gradiet pred da pravis backward pass. 
        model.zero_grad()        
        # Ivedi forward pass (evaluiraj model na trening batch).
        # ova go vrakja  loss (rather than the model output) zatoa so gi davame `labels`.
        outputs = model(b_input_ids, 
                    token_type_ids=None, 
                    attention_mask=b_input_mask, 
                    labels=b_labels)
        
        # Povikot do  `model` sekogas vrakja tuple, pa nie mora da ja izavidime
        # zagubata od torkata.
        loss = outputs[0]
        # sobiraj training loss niz site batches za da mozeme
        # da presmetame average loss na kraj. 

        total_loss += loss.item()
        #Izvedi backward pass za presmetuvanje na  gradienti.
        loss.backward()
        # namauvanje na normata na gradients na 1.0.
        # pomaga za da izbegneme  "exploding gradients" problemot
        torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
        # Update na  parametrite i koristi go cekorot sto go koristi presmetaniot gradient.
        # optimizerot go diktira "update rule"-kako parametrite se modificirani
        # soglasno nivniot gradients, learning rate, itn.
        optimizer.step()
        # Update learning rate.
        scheduler.step()
    # kalkuliraj average loss nad training data.
    avg_train_loss = total_loss / len(train_dataloader)            
    
    # zacuvaj loss value za "plotting the learning curve"
    loss_values.append(avg_train_loss)
    print("")
    print("  Average training loss: {0:.2f}".format(avg_train_loss))
    print("  Training epcoh took: {:}".format(format_time(time.time() - t0)))
        
    # ========================================
    #               Validation
    # ========================================
    # po kompletiranje nad sekoja training epoch, go smetame nasiot performans nad 
    # validation m-vo.
    print("")
    print("Running Validation...")
    t0 = time.time()
    model.eval()
    # sledenje na promenlivite/ variablite 
    eval_loss, eval_accuracy = 0, 0
    nb_eval_steps, nb_eval_examples = 0, 0
    # Evaluiranje data za edna epoha
    for batch in validation_dataloader:
        
        # dodadi batch na GPU
        batch = tuple(t.to(device) for t in batch)
        
        # Otpakuvaj inputi od dataloader
        b_input_ids, b_input_mask, b_labels = batch
        
        # ne cuvanje na  gradientite
        with torch.no_grad():        
            # Forward pass, calculira logit predictions.
            # ova vrakja logits mesto loss zatoa  so ne mu davame ovoj pat 'labels'.
            # token_type_ids e isto so i  "segment ids", koe sto
            # gi razlikuva  1 and 2 vo  2-recenici t.e zadaci.
    
            outputs = model(b_input_ids, 
                            token_type_ids=None, 
                            attention_mask=b_input_mask)
        
        # zemi "logits" output od modelot.  "logits" se vsusnost output
        #vrednosti pred da se primeni funkcija za aktiviranje kakosoftmax.
        logits = outputs[0]
        # premesti logits i  labels na CPU
        logits = logits.detach().cpu().numpy()
        label_ids = b_labels.to('cpu').numpy()
        
        # presmetaj accuracy za batch na test recenici.
        tmp_eval_accuracy = flat_accuracy(logits, label_ids)
        
        # akumuliraj t.e soberi  totalna tocnost/accuracy.
        eval_accuracy += tmp_eval_accuracy
        # vodi smetka za br na batches
        nb_eval_steps += 1
    # prikazi finalna tocnost za validacija.
    print("  Accuracy: {0:.2f}".format(eval_accuracy/nb_eval_steps))
    print("  Validation took: {:}".format(format_time(time.time() - t0)))
print("")
print("Training complete!")


======== Epoch 1 / 15 ========
Training...
  Batch    40  of     62.    Elapsed: 0:00:49.

  Average training loss: 3.10
  Training epcoh took: 0:01:15

Running Validation...
  Accuracy: 0.35
  Validation took: 0:00:03

======== Epoch 2 / 15 ========
Training...
  Batch    40  of     62.    Elapsed: 0:00:48.

  Average training loss: 2.44
  Training epcoh took: 0:01:14

Running Validation...
  Accuracy: 0.52
  Validation took: 0:00:03

======== Epoch 3 / 15 ========
Training...
  Batch    40  of     62.    Elapsed: 0:00:48.

  Average training loss: 1.98
  Training epcoh took: 0:01:14

Running Validation...
  Accuracy: 0.54
  Validation took: 0:00:03

======== Epoch 4 / 15 ========
Training...
  Batch    40  of     62.    Elapsed: 0:00:48.

  Average training loss: 1.61
  Training epcoh took: 0:01:14

Running Validation...
  Accuracy: 0.60
  Validation took: 0:00:03

======== Epoch 5 / 15 ========
Training...
  Batch    40  of     62.    Elapsed: 0:00:48.

  Average training loss: 1.3

In [ ]:
import plotly.express as px
f = pd.DataFrame(loss_values)
f.columns=['Loss']
fig = px.line(f, x=f.index, y=f.Loss)
fig.update_layout(title='Training loss of the Model',
                   xaxis_title='Epoch',
                   yaxis_title='Loss')
fig.show()

Test del


In [ ]:
labels

array([ 6, 34, 13, ..., 12, 12, 22])

In [ ]:
import pandas as pd

# kreiraj recenici i label listi
sentences = test.Questions.values
labels = test.Sentiment.values
# isto ko za train ista postapka samo za test
input_ids = []
#sekoja recenica....
for sent in sentences:
    # `encode` + cls ,pred,sep
  
    encoded_sent = tokenizer.encode(
                        sent,                      
                        add_special_tokens = True, 
                   )
    
    input_ids.append(encoded_sent)
# Pad  input tokens
input_ids = pad_sequences(input_ids, maxlen=MAX_LEN, 
                          dtype="long", truncating="post", padding="post")
# kreiraj attention  masks
attention_masks = []
# kreiraj mask za 1s sekoj token koj e sleden od  0s za padding
for seq in input_ids:
  seq_mask = [float(i>0) for i in seq]
  attention_masks.append(seq_mask) 
# Convertiraj vo  tensors.
prediction_inputs = torch.tensor(input_ids)
prediction_masks = torch.tensor(attention_masks)
prediction_labels = torch.tensor(labels)
# postavi batch size.  
batch_size = 32  
# kreiraj DataLoader.
prediction_data = TensorDataset(prediction_inputs, prediction_masks, prediction_labels)
prediction_sampler = SequentialSampler(prediction_data)
prediction_dataloader = DataLoader(prediction_data, sampler=prediction_sampler, batch_size=batch_size)

In [ ]:
# predviduvanja na  test set
print('Predicting labels for {:,} test sentences...'.format(len(prediction_inputs)))
# evauliraj model 
model.eval()
# sledi promenlivi
predictions , true_labels = [], []
# predvidi
for batch in prediction_dataloader:
  # dodadi batch na GPU
  batch = tuple(t.to(device) for t in batch)
  
  # Unpack the inputs from our dataloader
  b_input_ids, b_input_mask, b_labels = batch
  
  # da ne cuva gradienti    
  with torch.no_grad():
      # Forward pass, calculate logit predictions
      outputs = model(b_input_ids, token_type_ids=None, 
                      attention_mask=b_input_mask)
  logits = outputs[0]
  # premesti logits i labels vo CPU
  logits = logits.detach().cpu().numpy()
  label_ids = b_labels.to('cpu').numpy()
  
  # zacuvaj predvideni i vistinski labeli predictions and true labels
  predictions.append(logits)
  true_labels.append(label_ids)
print('DONE.')

Predicting labels for 605 test sentences...
DONE.


In [ ]:
true_labels

[array([3, 3, 3, 0, 0, 2, 0, 0, 0, 2, 2, 2, 2, 1, 1, 1, 3, 1, 1, 0, 0, 0,
        1, 1, 3, 3, 2, 2, 0, 0, 0, 3]),
 array([ 1,  1,  1,  3,  3,  3,  2,  2,  3,  3,  3,  3,  3,  3,  3,  0,  0,
         0,  3,  3,  3,  2,  2,  2,  2,  2,  2, 30,  5,  7,  4,  7]),
 array([ 9, 16,  4, 19, 23,  7, 33, 16,  3, 19, 12, 24,  0, 35,  3, 12, 22,
        13,  7, 18,  0,  8, 22, 22,  4,  3,  6, 20,  6, 35, 35, 22]),
 array([22,  6, 16,  7, 35, 17, 16,  1, 35,  5, 19, 35,  6, 23, 19,  6, 16,
         5,  2,  6,  7,  9,  5, 24, 22,  0,  6,  3, 19, 19,  2,  5]),
 array([18, 16,  0,  2,  4, 35,  2,  3, 35,  5, 22,  8,  3,  1, 10,  2, 35,
        35, 18, 22,  0, 16,  0, 35,  5,  2, 16,  5,  7, 23, 27, 11]),
 array([ 0,  4,  0, 22, 14,  7, 27, 18, 10,  5,  1,  1, 34,  3, 22,  7, 19,
        35,  5, 15,  0,  6, 19, 35, 16, 35,  1,  4, 20, 35,  5,  5]),
 array([16, 15,  2, 35,  5, 35,  2,  3, 16,  1,  0, 33, 19,  7, 16, 35,  1,
         8,  6,  7,  5,  5, 20,  6, 16,  5,  7,  5,  5, 24,  5,  8]),
 array([19

In [ ]:
predictions

[array([[ 2.6283312 ,  0.7276557 ,  1.020252  , ..., -1.4433935 ,
         -0.653481  ,  0.958957  ],
        [ 2.7361376 ,  2.439749  ,  0.33003902, ..., -1.1545782 ,
         -0.5607693 ,  0.8774007 ],
        [ 4.7432942 ,  2.1375947 ,  1.8637413 , ..., -0.6735747 ,
         -1.1040454 , -0.00869938],
        ...,
        [ 3.7167907 ,  2.608725  ,  3.345028  , ..., -0.28523582,
         -0.9417792 , -1.068047  ],
        [ 3.955473  ,  3.736404  ,  1.7469157 , ..., -0.27325457,
         -0.8131046 , -0.6093335 ],
        [ 2.1475942 ,  4.675297  ,  0.06354111, ..., -0.13121615,
         -0.2660778 , -0.53477436]], dtype=float32),
 array([[ 2.2411082 ,  5.5579357 ,  0.8422232 , ..., -0.08015819,
         -0.13314405, -0.27474728],
        [ 2.2411082 ,  5.5579357 ,  0.8422232 , ..., -0.08015819,
         -0.13314405, -0.27474728],
        [ 2.2411082 ,  5.5579357 ,  0.8422232 , ..., -0.08015819,
         -0.13314405, -0.27474728],
        ...,
        [ 0.05573349, -0.4461377 , -0.5

Merenja

In [ ]:
from sklearn.metrics import matthews_corrcoef
matthews_set = []
# Evaluate  na sekoj test batch so koristenje na  Matthew's correlation coefficient
print('Calculating Matthews Corr. Coef. for each batch...')
# za sekoj input batch...
for i in range(len(true_labels)):
  
  # predviduvanjata za sekoj batchs e  2-column ndarray (edna kolona za "0" 
  # i edna kolna za "1"). izberi recenica so najvisoka vrednosrt za labela i 
  # napravi ja kako lista od  0s i  1s.
  pred_labels_i = np.argmax(predictions[i], axis=1).flatten()
  # print(pred_labels_i)
  # Presmetaj i zacuvaj go  coef za dadeniot batch.  
  matthews = matthews_corrcoef(true_labels[i], pred_labels_i)                
  matthews_set.append(matthews)

Calculating Matthews Corr. Coef. for each batch...


In [ ]:
matthews_set

[0.3876561992308816,
 0.6007708676150975,
 0.774397068514671,
 0.934338539153302,
 0.8344017094017094,
 0.8328391075618589,
 0.7268570809498248,
 0.8052100807529393,
 0.7299710272164798,
 0.8259748375310426,
 0.8023504273504274,
 0.70096425423561,
 0.6978898086473796,
 0.7005900799982019,
 0.6982942430703625,
 0.6985112662398038,
 0.6671017804495861,
 0.9364427796516592,
 0.7835467939002064]

In [ ]:
# Combine the predictions for each batch into a single list of 0s and 1s.
flat_predictions = [item for sublist in predictions for item in sublist]
flat_predictions = np.argmax(flat_predictions, axis=1).flatten()
# Combine the correct labels for each batch into a single list.
flat_true_labels = [item for sublist in true_labels for item in sublist]
# Calculate the MCC
mcc = matthews_corrcoef(flat_true_labels, flat_predictions)
print('MCC: %.3f' % mcc)

MCC: 0.750


In [ ]:
flat_predictions

array([ 6,  6,  0,  0,  0,  2,  1,  0,  1,  2,  2,  2,  2,  1,  1,  1,  0,
        4,  4,  8,  1,  1,  1,  2,  2,  2,  2,  2,  1,  0,  0,  1,  1,  1,
        1,  3,  3,  3,  2,  2,  0,  6,  3,  5,  5, 12, 12,  5,  5,  5,  0,
        0,  0,  2,  2,  2,  2,  2,  2, 30,  5,  7,  4,  7,  9, 16,  4, 19,
       23,  7,  5, 16,  3, 19, 12,  5,  0, 35,  1, 12,  9, 16,  7, 18,  0,
        8, 22, 19,  4,  3,  6, 20, 35, 35, 35, 22, 22,  6, 16,  7, 35, 17,
       16,  1, 35, 24, 19, 35,  6, 23, 19,  6, 16,  6,  2,  6,  7,  9,  5,
       24, 22,  0,  6,  3, 19, 19,  2,  5, 18,  9,  1,  2,  1,  5,  2,  3,
       35,  5, 22,  8,  3,  1, 16,  2, 35, 35, 18, 22,  0, 16,  0, 35,  5,
        2, 16,  5,  7, 23, 27, 11,  1,  4,  0, 22, 14,  7, 35, 18, 10,  5,
        1,  1, 34,  3, 22,  7, 19, 35,  5,  6,  0, 35, 19, 35, 16, 35,  1,
        4, 20,  5,  5,  5, 16,  6,  2, 35,  5,  5, 16,  1, 16,  1,  0,  5,
       19,  7, 16, 35,  1,  8,  6,  7,  6,  5, 20,  6, 16,  8,  7,  5,  5,
        6,  5,  8, 19,  1

In [ ]:
import numpy as np
from sklearn.metrics import f1_score
def f1_score_func(preds, labels):
    # preds_flat = np.argmax(preds, axis=1).flatten()
    # labels_flat = labels.flatten()
    return f1_score(preds, labels, average = 'weighted')

In [ ]:
f1=f1_score_func(flat_predictions,flat_true_labels)
f1

0.775767716721545

In [ ]:
def accuracy_per_class(preds, labels):
    label_dict_inverse = {v: k for k, v in label_dict.items()}
    
    # preds_flat = np.argmax(preds, axis=1).flatten()
    # labels_flat = labels.flatten()
    
    for label in np.unique(labels):
        y_preds = preds[preds==label]
        y_true = labels[labels==label]
        print(f'Class: {label_dict_inverse[label]}')
        print(f'Accuracy:{len(y_preds[y_preds==label])}/{len(y_true)}\n')

In [ ]:
novo=pd.concat([trening, test], ignore_index=True, sort=False)
novo.Sentiment.unique()


array([ 6, 34, 13, 35,  5, 10, 24, 22,  2,  0,  4, 20,  7,  8, 16,  9, 19,
        1, 14, 18, 23,  3, 17, 27, 12, 30, 11, 31, 32, 15, 33, 25, 21, 29,
       28, 26])

In [ ]:
label_dict = {}
possible_labels = novo.Sentiment.unique()

for index, possible_label in enumerate(possible_labels):
    label_dict[possible_label] = index

In [ ]:
np.array(flat_true_labels)

array([ 3,  3,  3,  0,  0,  2,  0,  0,  0,  2,  2,  2,  2,  1,  1,  1,  3,
        1,  1,  0,  0,  0,  1,  1,  3,  3,  2,  2,  0,  0,  0,  3,  1,  1,
        1,  3,  3,  3,  2,  2,  3,  3,  3,  3,  3,  3,  3,  0,  0,  0,  3,
        3,  3,  2,  2,  2,  2,  2,  2, 30,  5,  7,  4,  7,  9, 16,  4, 19,
       23,  7, 33, 16,  3, 19, 12, 24,  0, 35,  3, 12, 22, 13,  7, 18,  0,
        8, 22, 22,  4,  3,  6, 20,  6, 35, 35, 22, 22,  6, 16,  7, 35, 17,
       16,  1, 35,  5, 19, 35,  6, 23, 19,  6, 16,  5,  2,  6,  7,  9,  5,
       24, 22,  0,  6,  3, 19, 19,  2,  5, 18, 16,  0,  2,  4, 35,  2,  3,
       35,  5, 22,  8,  3,  1, 10,  2, 35, 35, 18, 22,  0, 16,  0, 35,  5,
        2, 16,  5,  7, 23, 27, 11,  0,  4,  0, 22, 14,  7, 27, 18, 10,  5,
        1,  1, 34,  3, 22,  7, 19, 35,  5, 15,  0,  6, 19, 35, 16, 35,  1,
        4, 20, 35,  5,  5, 16, 15,  2, 35,  5, 35,  2,  3, 16,  1,  0, 33,
       19,  7, 16, 35,  1,  8,  6,  7,  5,  5, 20,  6, 16,  5,  7,  5,  5,
       24,  5,  8, 19,  1

In [ ]:
acc_klasi=accuracy_per_class(flat_predictions,np.array(flat_true_labels))

Class: 6
Accuracy:41/52

Class: 34
Accuracy:56/38

Class: 13
Accuracy:42/42

Class: 35
Accuracy:18/44

Class: 5
Accuracy:14/12

Class: 10
Accuracy:83/61

Class: 24
Accuracy:48/43

Class: 22
Accuracy:32/28

Class: 2
Accuracy:12/13

Class: 0
Accuracy:11/13

Class: 4
Accuracy:3/8

Class: 20
Accuracy:7/7

Class: 7
Accuracy:14/14

Class: 8
Accuracy:1/3

Class: 16
Accuracy:6/5

Class: 9
Accuracy:0/3

Class: 19
Accuracy:50/46

Class: 1
Accuracy:4/6

Class: 14
Accuracy:9/9

Class: 18
Accuracy:28/24

Class: 23
Accuracy:9/9

Class: 3
Accuracy:1/1

Class: 17
Accuracy:37/31

Class: 27
Accuracy:11/10

Class: 12
Accuracy:8/14

Class: 30
Accuracy:0/1

Class: 11
Accuracy:0/1

Class: 31
Accuracy:4/6

Class: 32
Accuracy:1/1

Class: 33
Accuracy:4/5

Class: 25
Accuracy:0/1

Class: 29
Accuracy:0/3

Class: 28
Accuracy:1/1

Class: 26
Accuracy:50/50

